---
- name: Download and unarchive grpcwebproxy
  ansible.builtin.unarchive:
    src: https://github.com/improbable-eng/grpc-web/releases/download/v0.13.0/grpcwebproxy-v0.13.0-arm6.zip
    dest: /usr/bin
    remote_src: yes
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
- name: copy the nginx config file and restart nginx
  copy:
    src: "{{ PROJECT_PATH }}/ansible/static_site.cfg"
    dest: /etc/nginx/sites-available/static_site.cfg
- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
- name: Push grpcwebproxy service
  copy:
    src: "{{ PROJECT_PATH }}/ansible/playbook/roles/setup_pi/files/grpcwebproxy.service"
    dest: /etc/systemd/system
- name: Push couscous_app service
  copy:
    src: "{{ PROJECT_PATH }}/ansible/playbook/roles/setup_pi/files/couscous_app.service"
    dest: /etc/systemd/system
