version: "3.4"

services:
  laughing-couscous:
    image: laughing-couscous
    container_name: laughing-couscous
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    privileged: true
    tty: true
    volumes:
      - ../..:/workspace/laughing-couscous:delegated
      - ccache:/var/ccache
      - vscode-server:/root/.vscode-server
    ports:
      - 3000:3000
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    depends_on:
      - laughing-couscous
    ports:
      - 8080:8080
volumes:
  ccache:
    external: false
  vscode-server:
    external: false
